
name: Léo Nicoletti
description: Senior Data Scientist
avatar: https://avatars1.githubusercontent.com/u/12911256?s=460&v=4
long_description: I am a research engineer in Grenoble, working on Machine learning and Applied mathematics problems. I have a strong interest in all AI-related fields and the emerging quantum information science. I graduated from the Grenoble Institute of Technology - Ensimag in 2016.

disqus:
google_analytics: UA-154208473-1
url:
baseurl: ""

# jekyll config.
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :expanded # or :compressed
gems:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
